### ISSUE TITLE
Problems on VPS debian.

### ISSUE THREAD

**Issue by d0xo** [nahamsec/bbht#16]
Installed the scriptfile on a fresh Debuan VPS,(not running Kali)
Box on Vultr 

Linux vultr.guest 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux

Getting this.
Listing subdomains using sublister...
Checking certspotter...
Checking http://crt.sh
Starting Massdns Subdomain discovery this may take a while
Massdns finished...
Started dns records check...
Looking into CNAME Records...
Starting discovery...
Probing for live hosts...
./lazyrecon.sh: line 74: httprobe: command not found
cat: ./greenpilled.com/recon-2019-07-30/urllist.txt: No such file or directory
Total of 1 live subdomains were found
Taking screenshots...
[+] 0 URLs to be screenshot
[+] 0 actual URLs screenshot
[+] 0 error(s)
Scraping wayback for data...
./lazyrecon.sh: line 49: waybackurls: command not found
./lazyrecon.sh: line 50: unfurl: command not found
Starting dirsearch..
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 11, in <module>
    load_entry_point('Interlace==1.5.3', 'console_scripts', 'interlace')()
  File "/usr/local/lib/python3.7/dist-packages/Interlace-1.5.3-py3.7.egg/Interlace/interlace.py", line 24, in main
  File "/usr/local/lib/python3.7/dist-packages/Interlace-1.5.3-py3.7.egg/Interlace/interlace.py", line 10, in build_queue
  File "/usr/local/lib/python3.7/dist-packages/Interlace-1.5.3-py3.7.egg/Interlace/lib/core/input.py", line 199, in process_commands
Exception: No target provided, or empty target list
Scan for xxx.com finished successfully
Scan completed in : 3 minutes and 13 seconds.

Not fully working, no screenshots for instance

**Comment by gauravdrago** [comment]
try installing those required things manually

**Comment by RiRa12621** [comment]
Seems gopath is not part of your PATH and therefore you get `command not found` for go binaries that are used like `unfurl` and `waybackurls` 
With that the whole script breaks right at the beginning causing cascading errors
